{{- range $serviceName, $serviceConfig := .Values.services }}
{{- if $serviceConfig.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-chart.fullname" $ }}-{{ $serviceName }}
  labels:
    {{- include "generic-chart.labels" $ | nindent 4 }}
    service-name: {{ $serviceName | quote }}
    {{- with $serviceConfig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $serviceConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $serviceConfig.type | default "ClusterIP" }}
  ports:
    - port: {{ $serviceConfig.port }}
      targetPort: {{ $serviceConfig.targetPort | default $serviceConfig.port }}
      protocol: {{ $serviceConfig.protocol | default "TCP" }}
      name: {{ $serviceConfig.portName | default "http" }}
      {{- if and (eq ($serviceConfig.type | default "ClusterIP") "NodePort") $serviceConfig.nodePort }}
      nodePort: {{ $serviceConfig.nodePort }}
      {{- end }}
  selector:
    {{- include "generic-chart.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}