{{- if and .Values.externalSecrets .Values.externalSecrets.enabled .Values.externalSecrets.es }}
{{- range $secretName, $secretConfig := .Values.externalSecrets.es }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "generic-chart.fullname" $ }}-{{ $secretName }}
  labels:
    {{- include "generic-chart.labels" $ | nindent 4 }}
    external-secret-name: {{ $secretName | quote }}
    {{- $esLabels := list }}
    {{/* Global external secrets labels */}}
    {{- if $.Values.externalSecrets.labels }}
      {{- $esLabels = append $esLabels $.Values.externalSecrets.labels }}
    {{- end }}
    {{/* Individual external secret labels */}}
    {{- if $secretConfig.labels }}
      {{- $esLabels = append $esLabels $secretConfig.labels }}
    {{- end }}
    {{- if $esLabels }}
    {{- include "generic-chart.mergeLabels" $esLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $.Values.externalSecrets.update_config }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    {{- else }}
    "helm.sh/hook": "pre-install"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- $esAnnotations := list }}
    {{/* Global external secrets annotations */}}
    {{- if $.Values.externalSecrets.annotations }}
      {{- $esAnnotations = append $esAnnotations $.Values.externalSecrets.annotations }}
    {{- end }}
    {{/* Individual external secret annotations */}}
    {{- if $secretConfig.annotations }}
      {{- $esAnnotations = append $esAnnotations $secretConfig.annotations }}
    {{- end }}
    {{- if $esAnnotations }}
    {{- include "generic-chart.mergeAnnotations" $esAnnotations | nindent 4 }}
    {{- end }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval | default "15s" }}
  secretStoreRef:
    name: {{ $.Values.externalSecrets.name }}
    kind: {{ $.Values.externalSecrets.kind | default "SecretStore" }}
  target:
    name: {{ include "generic-chart.fullname" $ }}-{{ $secretName }}
    creationPolicy: {{ $secretConfig.creationPolicy | default "Owner" }}
    {{- if $secretConfig.template }}
    template:
      {{- toYaml $secretConfig.template | nindent 6 }}
    {{- end }}
  
  {{- if $secretConfig.data }}
  data:
  {{- range $dataKey, $dataValue := $secretConfig.data }}
    - secretKey: {{ $dataKey }}
      remoteRef:
        {{- if $dataValue.conversionStrategy }}
        conversionStrategy: {{ $dataValue.conversionStrategy }}
        {{- else }}
        conversionStrategy: Default
        {{- end }}
        {{- if $dataValue.decodingStrategy }}
        decodingStrategy: {{ $dataValue.decodingStrategy }}
        {{- else }}
        decodingStrategy: None
        {{- end }}
        {{- if $dataValue.key }}
        key: {{ $dataValue.key }}
        {{- else if $.Values.externalSecrets.key }}
        key: {{ $.Values.externalSecrets.key }}
        {{- else }}
        {{- fail "Either individual data key or global key must be specified" }}
        {{- end }}
        {{- if and (eq $.Values.externalSecrets.cloud "aws") $dataValue.property }}
        property: {{ $dataValue.property }}
        {{- end }}
        {{- if and (eq $.Values.externalSecrets.cloud "gcp") $dataValue.version }}
        version: {{ $dataValue.version }}
        {{- end }}
        {{- if and (eq $.Values.externalSecrets.cloud "azure") $dataValue.version }}
        version: {{ $dataValue.version }}
        {{- end }}
  {{- end }}
  {{- end }}
  
  {{- if $secretConfig.dataFrom }}
  dataFrom:
  {{- range $dataFrom := $secretConfig.dataFrom }}
    {{- if $dataFrom.extract }}
    - extract:
        key: {{ $dataFrom.extract.key }}
        {{- if $dataFrom.extract.conversionStrategy }}
        conversionStrategy: {{ $dataFrom.extract.conversionStrategy }}
        {{- else }}
        conversionStrategy: Default
        {{- end }}
        {{- if $dataFrom.extract.decodingStrategy }}
        decodingStrategy: {{ $dataFrom.extract.decodingStrategy }}
        {{- else }}
        decodingStrategy: None
        {{- end }}
        {{- if and (eq $.Values.externalSecrets.cloud "aws") $dataFrom.extract.property }}
        property: {{ $dataFrom.extract.property }}
        {{- end }}
        {{- if and (eq $.Values.externalSecrets.cloud "gcp") $dataFrom.extract.version }}
        version: {{ $dataFrom.extract.version }}
        {{- end }}
        {{- if and (eq $.Values.externalSecrets.cloud "azure") $dataFrom.extract.version }}
        version: {{ $dataFrom.extract.version }}
        {{- end }}
    {{- end }}
    {{- if $dataFrom.find }}
    - find:
        {{- if $dataFrom.find.name }}
        name:
          {{- if $dataFrom.find.name.regexp }}
          regexp: {{ $dataFrom.find.name.regexp | quote }}
          {{- end }}
        {{- end }}
        {{- if $dataFrom.find.path }}
        path: {{ $dataFrom.find.path }}
        {{- end }}
        {{- if $dataFrom.find.tags }}
        tags:
          {{- toYaml $dataFrom.find.tags | nindent 10 }}
        {{- end }}
        {{- if $dataFrom.find.conversionStrategy }}
        conversionStrategy: {{ $dataFrom.find.conversionStrategy }}
        {{- else }}
        conversionStrategy: Default
        {{- end }}
        {{- if $dataFrom.find.decodingStrategy }}
        decodingStrategy: {{ $dataFrom.find.decodingStrategy }}
        {{- else }}
        decodingStrategy: None
        {{- end }}
    {{- end }}
    {{- if $dataFrom.rewrite }}
    - rewrite:
        {{- range $rewrite := $dataFrom.rewrite }}
        - regexp:
            source: {{ $rewrite.regexp.source | quote }}
            target: {{ $rewrite.regexp.target | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}