{{- range $secretName, $secretConfig := .Values.secrets }}
{{- if $secretConfig.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-chart.fullname" $ }}-{{ $secretName }}
  labels:
    {{- include "generic-chart.labels" $ | nindent 4 }}
    secret-name: {{ $secretName | quote }}
    {{- with $secretConfig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $secretConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ $secretConfig.type | default "Opaque" }}
{{- if $secretConfig.data }}
data:
  {{- toYaml $secretConfig.data | nindent 2 }}
{{- end }}
{{- if $secretConfig.stringData }}
stringData:
  {{- toYaml $secretConfig.stringData | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}