{{/* workloads.yaml */}}

{{- if eq .Values.workload.type "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-chart.fullname" . }}
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workload.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "generic-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "generic-chart.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- include "generic-chart.podTemplate" (dict "globalConfig" . "podConfig" .Values.podTemplate) | nindent 4 }}
{{- end }}

{{- if eq .Values.workload.type "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "generic-chart.fullname" . }}
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "generic-chart.fullname" . }}
  replicas: {{ .Values.workload.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "generic-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "generic-chart.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- include "generic-chart.podTemplate" (dict "globalConfig" . "podConfig" .Values.podTemplate) | nindent 4 }}
  {{- with .Values.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if eq .Values.workload.type "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "generic-chart.fullname" . }}
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "generic-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "generic-chart.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- include "generic-chart.podTemplate" (dict "globalConfig" . "podConfig" .Values.podTemplate) | nindent 4 }}
{{- end }}