{{- range $cronJobName, $cronJobConfig := .Values.cronjobs }}
{{- if $cronJobConfig.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic-chart.fullname" $ }}-{{ $cronJobName }}
  labels:
    {{- include "generic-chart.labels" $ | nindent 4 }}
    cronjob-name: {{ $cronJobName }}
spec:
  schedule: {{ $cronJobConfig.schedule | quote }}
  concurrencyPolicy: {{ $cronJobConfig.concurrencyPolicy | default "Allow" }}
  failedJobsHistoryLimit: {{ $cronJobConfig.failedJobsHistoryLimit | default 1 }}
  successfulJobsHistoryLimit: {{ $cronJobConfig.successfulJobsHistoryLimit | default 3 }}
  {{- with $cronJobConfig.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  suspend: {{ $cronJobConfig.suspend | default false }}
  jobTemplate:
    spec:
      {{- with $cronJobConfig.jobTemplate.backoffLimit }}
      backoffLimit: {{ . }}
      {{- end }}
      {{- with $cronJobConfig.jobTemplate.completions }}
      completions: {{ . }}
      {{- end }}
      {{- with $cronJobConfig.jobTemplate.parallelism }}
      parallelism: {{ . }}
      {{- end }}
      {{- with $cronJobConfig.jobTemplate.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . }}
      {{- end }}
      {{- with $cronJobConfig.jobTemplate.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ . }}
      {{- end }}
      template:
        {{- $cronJobPodConfig := dict 
            "restartPolicy" ($cronJobConfig.jobTemplate.restartPolicy | default "OnFailure")
            "additionalLabels" (dict "cronjob-name" $cronJobName)
        }}
        {{- $cronJobContainerConfig := dict 
            "name" $cronJobName
            "repository" ($cronJobConfig.image.repository | default $.Values.image.repository)
            "tag" ($cronJobConfig.image.tag | default $.Values.image.tag)
            "pullPolicy" ($cronJobConfig.image.pullPolicy | default $.Values.image.pullPolicy)
            "command" $cronJobConfig.command
            "args" $cronJobConfig.args
            "env" $cronJobConfig.env
            "envFrom" $cronJobConfig.envFrom
            "resources" ($cronJobConfig.resources | default $.Values.resources)
            "volumeMounts" $cronJobConfig.volumeMounts
            "volumes" $cronJobConfig.volumes
            "sidecarContainers" $cronJobConfig.sidecarContainers
        }}
        {{- include "generic-chart.podTemplate" (dict 
            "globalConfig" $ 
            "podConfig" $cronJobPodConfig 
            "containerConfig" $cronJobContainerConfig
        ) | nindent 8 }}
{{- end }}
{{- end }}