{{- range $jobName, $jobConfig := .Values.jobs }}
{{- if $jobConfig.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "generic-chart.fullname" $ }}-{{ $jobName }}
  labels:
    {{- include "generic-chart.labels" $ | nindent 4 }}
    job-name: {{ $jobName }}
spec:
  {{- with $jobConfig.backoffLimit }}
  backoffLimit: {{ . }}
  {{- end }}
  {{- with $jobConfig.completions }}
  completions: {{ . }}
  {{- end }}
  {{- with $jobConfig.parallelism }}
  parallelism: {{ . }}
  {{- end }}
  {{- with $jobConfig.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with $jobConfig.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  template:
    {{- $jobPodConfig := dict 
        "restartPolicy" ($jobConfig.restartPolicy | default "OnFailure")
        "additionalLabels" (dict "job-name" $jobName)
    }}
    {{- $jobContainerConfig := dict 
        "name" $jobName
        "repository" ($jobConfig.image.repository | default $.Values.image.repository)
        "tag" ($jobConfig.image.tag | default $.Values.image.tag)
        "pullPolicy" ($jobConfig.image.pullPolicy | default $.Values.image.pullPolicy)
        "command" $jobConfig.command
        "args" $jobConfig.args
        "env" $jobConfig.env
        "envFrom" $jobConfig.envFrom
        "resources" ($jobConfig.resources | default $.Values.resources)
        "volumeMounts" $jobConfig.volumeMounts
        "volumes" $jobConfig.volumes
        "sidecarContainers" $jobConfig.sidecarContainers
    }}
    {{- include "generic-chart.podTemplate" (dict 
        "globalConfig" $ 
        "podConfig" $jobPodConfig 
        "containerConfig" $jobContainerConfig
    ) | nindent 4 }}
{{- end }}
{{- end }}