# secret.yaml
{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-chart.fullname" . }}
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}