{{- range $configMapName, $configMapConfig := .Values.configMaps }}
{{- if $configMapConfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-chart.fullname" $ }}-{{ $configMapName }}
  labels:
    {{- include "generic-chart.labels" $ | nindent 4 }}
    configmap-name: {{ $configMapName | quote }}
    {{- with $configMapConfig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $configMapConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if $configMapConfig.data }}
data:
  {{- toYaml $configMapConfig.data | nindent 2 }}
{{- end }}
{{- if $configMapConfig.binaryData }}
binaryData:
  {{- toYaml $configMapConfig.binaryData | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}