{{- if eq .Values.workload.type "deployment" }}
{{- if .Values.workload.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-chart.fullname" . }}
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
    {{- $workloadLabels := list }}
    {{- if .Values.workloadLabels }}
      {{- $workloadLabels = append $workloadLabels .Values.workloadLabels }}
    {{- end }}
    {{- if .Values.workload.labels }}
      {{- $workloadLabels = append $workloadLabels .Values.workload.labels }}
    {{- end }}
    {{- if .Values.workload.deployment.labels }}
      {{- $workloadLabels = append $workloadLabels .Values.workload.deployment.labels }}
    {{- end }}
    {{- if $workloadLabels }}
    {{- include "generic-chart.mergeLabels" $workloadLabels | nindent 4 }}
    {{- end }}
  {{- $workloadAnnotations := list }}
  {{- if .Values.workloadAnnotations }}
    {{- $workloadAnnotations = append $workloadAnnotations .Values.workloadAnnotations }}
  {{- end }}
  {{- if .Values.workload.annotations }}
    {{- $workloadAnnotations = append $workloadAnnotations .Values.workload.annotations }}
  {{- end }}
  {{- if .Values.workload.deployment.annotations }}
    {{- $workloadAnnotations = append $workloadAnnotations .Values.workload.deployment.annotations }}
  {{- end }}
  {{- if $workloadAnnotations }}
  annotations:
    {{- include "generic-chart.mergeAnnotations" $workloadAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.workload.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic-chart.selectorLabels" . | nindent 6 }}
  {{- with .Values.workload.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.workload.deployment.revisionHistoryLimit }}
  template:
    {{- include "generic-chart.podTemplate" (dict "globalConfig" . "podConfig" (dict)) | nindent 4 }}
{{- end }}
{{- end }}

---
{{- if eq .Values.workload.type "statefulset" }}
{{- if .Values.workload.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "generic-chart.fullname" . }}
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
    {{- $workloadLabels := list }}
    {{- if .Values.workloadLabels }}
      {{- $workloadLabels = append $workloadLabels .Values.workloadLabels }}
    {{- end }}
    {{- if .Values.workload.labels }}
      {{- $workloadLabels = append $workloadLabels .Values.workload.labels }}
    {{- end }}
    {{- if .Values.workload.statefulset.labels }}
      {{- $workloadLabels = append $workloadLabels .Values.workload.statefulset.labels }}
    {{- end }}
    {{- if $workloadLabels }}
    {{- include "generic-chart.mergeLabels" $workloadLabels | nindent 4 }}
    {{- end }}
  {{- $workloadAnnotations := list }}
  {{- if .Values.workloadAnnotations }}
    {{- $workloadAnnotations = append $workloadAnnotations .Values.workloadAnnotations }}
  {{- end }}
  {{- if .Values.workload.annotations }}
    {{- $workloadAnnotations = append $workloadAnnotations .Values.workload.annotations }}
  {{- end }}
  {{- if .Values.workload.statefulset.annotations }}
    {{- $workloadAnnotations = append $workloadAnnotations .Values.workload.statefulset.annotations }}
  {{- end }}
  {{- if $workloadAnnotations }}
  annotations:
    {{- include "generic-chart.mergeAnnotations" $workloadAnnotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.workload.statefulset.replicas }}
  selector:
    matchLabels:
      {{- include "generic-chart.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Values.workload.statefulset.serviceName | default (include "generic-chart.fullname" .) }}
  podManagementPolicy: {{ .Values.workload.statefulset.podManagementPolicy }}
  {{- with .Values.workload.statefulset.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    {{- include "generic-chart.podTemplate" (dict "globalConfig" . "podConfig" (dict)) | nindent 4 }}
  {{- with .Values.workload.statefulset.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}

---
{{- if eq .Values.workload.type "daemonset" }}
{{- if .Values.workload.daemonset.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "generic-chart.fullname" . }}
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
    {{- $workloadLabels := list }}
    {{- if .Values.workloadLabels }}
      {{- $workloadLabels = append $workloadLabels .Values.workloadLabels }}
    {{- end }}
    {{- if .Values.workload.labels }}
      {{- $workloadLabels = append $workloadLabels .Values.workload.labels }}
    {{- end }}
    {{- if .Values.workload.daemonset.labels }}
      {{- $workloadLabels = append $workloadLabels .Values.workload.daemonset.labels }}
    {{- end }}
    {{- if $workloadLabels }}
    {{- include "generic-chart.mergeLabels" $workloadLabels | nindent 4 }}
    {{- end }}
  {{- $workloadAnnotations := list }}
  {{- if .Values.workloadAnnotations }}
    {{- $workloadAnnotations = append $workloadAnnotations .Values.workloadAnnotations }}
  {{- end }}
  {{- if .Values.workload.annotations }}
    {{- $workloadAnnotations = append $workloadAnnotations .Values.workload.annotations }}
  {{- end }}
  {{- if .Values.workload.daemonset.annotations }}
    {{- $workloadAnnotations = append $workloadAnnotations .Values.workload.daemonset.annotations }}
  {{- end }}
  {{- if $workloadAnnotations }}
  annotations:
    {{- include "generic-chart.mergeAnnotations" $workloadAnnotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "generic-chart.selectorLabels" . | nindent 6 }}
  {{- with .Values.workload.daemonset.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    {{- include "generic-chart.podTemplate" (dict "globalConfig" . "podConfig" (dict)) | nindent 4 }}
{{- end }}
{{- end }}

---
{{- if eq .Values.workload.type "rollout" }}
{{- if .Values.workload.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "generic-chart.fullname" . }}
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
    {{- $workloadLabels := list }}
    {{- if .Values.workloadLabels }}
      {{- $workloadLabels = append $workloadLabels .Values.workloadLabels }}
    {{- end }}
    {{- if .Values.workload.labels }}
      {{- $workloadLabels = append $workloadLabels .Values.workload.labels }}
    {{- end }}
    {{- if .Values.workload.rollout.labels }}
      {{- $workloadLabels = append $workloadLabels .Values.workload.rollout.labels }}
    {{- end }}
    {{- if $workloadLabels }}
    {{- include "generic-chart.mergeLabels" $workloadLabels | nindent 4 }}
    {{- end }}
  {{- $workloadAnnotations := list }}
  {{- if .Values.workloadAnnotations }}
    {{- $workloadAnnotations = append $workloadAnnotations .Values.workloadAnnotations }}
  {{- end }}
  {{- if .Values.workload.annotations }}
    {{- $workloadAnnotations = append $workloadAnnotations .Values.workload.annotations }}
  {{- end }}
  {{- if .Values.workload.rollout.annotations }}
    {{- $workloadAnnotations = append $workloadAnnotations .Values.workload.rollout.annotations }}
  {{- end }}
  {{- if $workloadAnnotations }}
  annotations:
    {{- include "generic-chart.mergeAnnotations" $workloadAnnotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.workload.rollout.replicas }}
  selector:
    matchLabels:
      {{- include "generic-chart.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.workload.rollout.revisionHistoryLimit }}
  {{- with .Values.workload.rollout.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    {{- include "generic-chart.podTemplate" (dict "globalConfig" . "podConfig" (dict)) | nindent 4 }}
{{- end }}
{{- end }}