# Business Labels - Applied to all resources
businessLabels:
  env: "production"


# Image configuration
image:
  repository: "108177350548.dkr.ecr.us-east-1.amazonaws.com/booking-service"
  tag: "v0.0.1-pre337-b043581"

imagePullSecrets: []


# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 1536Mi
  requests:
    cpu: 500m
    memory: 1536Mi


# Environment variables in key=value format
envVars:
  AWS_ACCOUNTID: "723008196684"
  ENVIRONMENTVARIABLES_USERSERVICEURL: "https://user-api.fourkites.com"
  FEATURE_LIMITSTATUS: "Subscription Created"
  # Arrays are handled differently - convert to JSON or comma-separated
  FEATURE_UPDATEBOOKING: '["ford-india-ocean-pilot", "test-ocean-shipper"]'


# Workload Configuration - Using Argo Rollouts
workload:
  type: rollout
  
  # Deployment specific settings (not used with rollouts)
  deployment:
    enabled: false
  
  # StatefulSet specific settings
  statefulset:
    enabled: false
  
  # DaemonSet specific settings
  daemonset:
    enabled: false
  
  # Argo Rollouts specific settings
  rollout:
    enabled: true
    replicas: 6
    revisionHistoryLimit: 10
    strategy:
      blueGreen:
        autoPromotionEnabled: false
        activeService: booking-service
        previewService: booking-service-preview
        previewReplicaCount: 1
        scaleDownDelaySeconds: 30



# External Secrets Configuration
externalSecrets:
  enabled: true
  refreshInterval: "5m"
  name: "prod-cluster-secretstore"
  kind: "ClusterSecretStore"
  cloud: "aws"

# Advanced Ingress with Active/Preview Support
ingress:
  labels: {}
  labels_active: {}
  labels_preview: {}
  annotations:
    kubernetes.io/ingress.class: "nginx"
  annotations_active: {}
  annotations_preview: {}
  
  data:
    fk-ingress:
      enabled: true
      annotations:
        appgw.ingress.kubernetes.io/appgw-ssl-certificate: "wildcard-fourkites-ssl"
      className: "nginx"
      hosts:
        - host: "booking-api.fourkites.com"
          host_preview: "booking-api-preview.fourkites.com"
          paths:
            - path: /
              pathType: Prefix

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
