# Converted values-default.yaml for booking-service
# This is a YAML-formatted file.

# Global settings
global:
  nameOverride: "booking-service"
  fullnameOverride: "booking-service"

# Business Labels - Applied to all resources
businessLabels:
  bu: "logistics"
  project: "booking-service"
  application: "booking-api"
  env: "local"
  team: "ocean-team"
  cloud: ""

# Image configuration
image:
  repository: "108177350548.dkr.ecr.us-east-1.amazonaws.com/booking-service"
  pullPolicy: Always
  tag: "release_v2.42.1-216b294"

imagePullSecrets: []

# Service Account
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::300982737966:role/booking-service-role"
  name: "booking-service-sa"

# Pod Security Context
podSecurityContext: {}

# Container Security Context
securityContext: {}

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 8092M
  requests:
    cpu: 1300m
    memory: 8092M

# Node selector
nodeSelector:
  product: ocean

# Tolerations
tolerations:
  - key: "product"
    operator: "Equal"
    value: "ocean"
    effect: "NoSchedule"

# Affinity
affinity: {}

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Environment variables in key=value format
envVars:
  BOOKING_SERVICE_URL: "http://booking-api.fourkites.com"
  COMPANY_SERVICE_URL: "http://company-api.fourkites.com"
  DS_OCEAN_SERVICE_URL: "http://ds-ocean.fourkites.com"
  FOURKITES_APP_ID: "booking-service"
  FOURKITES_BASE_URL: "https://app.fourkites.com"
  OTEL_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-collector.telemetry:4317"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=booking-service,deployment.environment=$(FK_ENVIRONMENT),service.instance.id=$(POD_NAME),k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(NAMESPACE_NAME),k8s.node.name=$(NODE_NAME)"
  OTEL_SERVICE_NAME: "booking-service"
  TELEMETRY_ENABLED: "true"
  OTEL_TRACES_SAMPLER: "traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "0.05"
  OTEL_CONTRIB_VERSION: "0.102.0"
  DB_MAXCONNECTIONS: "4"
  DB_MAXIDLECONNECTIONS: "4"
  DB_PORT: "5432"
  DB_SSLMODE: "disable"
  LOGGER_DIRECTORY: "/var/log/"
  LOGGER_LOGLEVEL: "INFO"
  LOG_TO_STDOUT: "true"
  AWS_MULTIMODALQUEUESUFFIX: "-multimodal-worker"
  AWS_REGION: "us-east-1"
  SERVER_PORT: ":5000"

# Environment variables from valueFrom (template format)
env:
  - name: ENV
    value: "local"
  - name: FK_ENVIRONMENT
    value: "local"
  - name: FK_ENV
    value: "local"
  - name: LOGGER_FILENAME
    value: "booking-service-local.log"

# Environment variables from ConfigMap/Secret
envFrom:
  - secretRef:
      name: booking-service-db-secrets
  - secretRef:
      name: booking-service-fourkites-secrets
  - secretRef:
      name: booking-service-github-token

# Volume mounts (none specified in original)
volumeMounts: []

# Volumes (none specified in original)
volumes: []

# Init containers (none specified in original)
initContainers: []

# Sidecar containers (none specified in original)
sidecarContainers: []

# Workload Configuration
workload:
  type: deployment
  
  # Deployment specific settings
  deployment:
    enabled: true
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 3
  
  # StatefulSet specific settings
  statefulset:
    enabled: false
  
  # DaemonSet specific settings
  daemonset:
    enabled: false
  
  # Argo Rollouts specific settings
  rollout:
    enabled: false

# Jobs Configuration (none in original)
jobs: {}

# CronJobs Configuration (none in original)
cronjobs: {}

# Multiple Services Configuration (none specified)
services: {}

# Single Service configuration
service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 5000
  annotations: {}

# Multiple ConfigMaps
configMaps: {}

# Multiple Secrets (none in original, handled by external secrets)
secrets: {}

# External Secrets Configuration
externalSecrets:
  enabled: true
  refreshInterval: "5m"
  name: "booking-service"
  kind: "ClusterSecretStore"
  cloud: "aws"
  
  labels: {}
  annotations: {}
  
  es:
    db-secrets:
      data:
        DB_HOST:
          key: "booking-service"
          property: "DB_HOST"
          decodingStrategy: "None"
          conversionStrategy: "Default"
        DB_DBNAME:
          key: "booking-service"
          property: "DB_DBNAME"
          decodingStrategy: "None"
          conversionStrategy: "Default"
        BOOKING_SERVICE_MIGRATION_USER:
          key: "booking-service"
          property: "BOOKING_SERVICE_MIGRATION_USER"
          decodingStrategy: "None"
          conversionStrategy: "Default"
        BOOKING_SERVICE_MIGRATION_PASSWORD:
          key: "booking-service"
          property: "BOOKING_SERVICE_MIGRATION_PASSWORD"
          decodingStrategy: "None"
          conversionStrategy: "Default"
        DB_USER:
          key: "booking-service"
          property: "DB_USER"
          decodingStrategy: "None"
          conversionStrategy: "Default"
        DB_PASSWORD:
          key: "booking-service"
          property: "DB_PASSWORD"
          decodingStrategy: "None"
          conversionStrategy: "Default"
    
    fourkites-secrets:
      data:
        ENVIRONMENTVARIABLES_FOURKITESAPPID:
          key: "booking-service"
          property: "ENVIRONMENTVARIABLES_FOURKITESAPPID"
          decodingStrategy: "None"
          conversionStrategy: "Default"
        ENVIRONMENTVARIABLES_SHAREDAPPSECRET:
          key: "booking-service"
          property: "ENVIRONMENTVARIABLES_SHAREDAPPSECRET"
          decodingStrategy: "None"
          conversionStrategy: "Default"
    
    github-token:
      data:
        GITHUB_TOKEN:
          key: "booking-service"
          property: "GITHUB_TOKEN"
          decodingStrategy: "None"
          conversionStrategy: "Default"

# Advanced Ingress with Active/Preview Support
ingress:
  labels: {}
  labels_active: {}
  labels_preview: {}
  annotations: {}
  annotations_active: {}
  annotations_preview: {}
  
  data:
    fk-ingress:
      enabled: true
      annotations:
        appgw.ingress.kubernetes.io/appgw-ssl-certificate: "wildcard-fourkites-ssl"
      className: "nginx"
      hosts:
        - host: "booking-api.fourkites.com"
          host_preview: "booking-api-preview.fourkites.com"
          paths:
            - path: /
              pathType: Prefix

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: "2"

# Persistence (not used)
persistence:
  enabled: false

# Health checks
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /internal/v1/health_check
    port: 5000
    scheme: HTTP
  periodSeconds: 40
  successThreshold: 1
  timeoutSeconds: 10

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /internal/v1/health_check
    port: 5000
    scheme: HTTP
  periodSeconds: 40
  successThreshold: 1
  timeoutSeconds: 10

startupProbe: {}

# Custom notes for NOTES.txt
customNotes: |
  Welcome to Booking Service!

  To access the booking API:
  1. Internal: http://booking-service.default.svc.cluster.local
  2. External: Use the Ingress URL (if configured)
  
  For support: contact@example.com

# Additional configurations
automountServiceAccountToken: false
revisionHistoryLimit: 3
update_config: true